Hw9
Klopotovskyi/JS pull request #4
Opened 2019-01-18 12:24 UTC by Klopotovskyi

2019-01-19 15:01 UTC, spolischook requested changes

2019-01-19 15:01 UTC, spolischook commented on hw_9.js
> +getPost(function(callback) {
ти викликаєш `getPost` і передаєш аргументом колбек, а аргумент у тебе у функції не вказано. 
```suggestion
getPost(function(responseText) {
  console.log(JSON.parse(responseText))
}
```

2019-01-24 16:14 UTC, spolischook requested changes

2019-01-24 16:14 UTC, spolischook commented on hw_9.js
> +    setTimeout(GetPostByAsync, 2500);
you should work with result of async function as with promise, see:

    async ensures that the function returns a promise, and wraps non-promises in it.

https://javascript.info/async-await#async-functions

2019-01-24 16:14 UTC, spolischook commented on hw_9.js
> +                 reject(this.status);
I saw this error somewhere... (copy-paste) this line of code will never execute, and it shouldn't be here. Why you want to reject response with 200 status code?

2019-01-24 16:14 UTC, spolischook commented on hw_9.js
> +    function GetPostByPromise() {
return Promise, and move work with it  (then, catch) out of scope of function

2019-01-24 16:29 UTC, Klopotovskyi commented on hw_9.js
> +                 reject(this.status);
согласен. Но по идее эта строчка может стоять вне if но в границах задавания промиса GetbyPromise?

2019-01-24 16:44 UTC, spolischook commented on hw_9.js
> +                 reject(this.status);
Прочитай пожалуйста это https://en.wikipedia.org/wiki/List_of_HTTP_status_codes (можешь переключить язык на удобный тебе)
И вот это https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest/readyState
А теперь вопрос при каком `readyState` и при каком `status` мы вызовем `reject` метод?

2019-02-15 15:13 UTC, merged